### ISSUE TITLE
[BUG] Failed to construct URL

### ISSUE THREAD

**Issue by oktapodia** [wavesplatform/waves-keeper#100]
**Describe the bug**

When interacting with a canvas, I am seeing that error in the console + the code injected can break some canvas application I am interacting with

**To Reproduce**
1. Go to 'http://draw.io/'
2. Add a svg image element to the canvas
3. Double click the element on the canvas

**Expected behavior**

I can see that this is coming from the `checkForPaymentApiLink` function which is checking the `href` property which exists in `a` element but also in the `SVGAnimatedString` element.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser/JVM chrome
 - Version 1.2.1

**Additional context**

**Comment by isakovanton** [comment]
Fixed in #111
