### ISSUE TITLE
[BUG] @bable/polyfill error

### ISSUE THREAD

**Issue by kf106** [wavesplatform/waves-keeper#169]
**Describe the bug**
If the inspect page is open on console while using the wallet, the following warning is seen:

ui.js?9fa45892bcecf24d5477:29 @babel/polyfill is loaded more than once on this page. This is probably not desirable/intended and may have consequences if different versions of the polyfills are applied sequentially. If you do need to load the polyfill more than once, use @babel/polyfill/noConflict instead to bypass the warning.

**To Reproduce**
Open the wallet
Right-click and select "inspect"
In the pop-up, select console
Observe the error message

**Expected behavior**
There should be no warnings or errors visible on inspect

**Screenshots**

**Environment**
Please complete the following information.

- Version of ProviderKeeper: 1.5.2
- OS: [e.g. Ubuntu 20.04
- Browser version: Version 1.32.115 Chromium: 96.0.4664.93 (Official Build) (64-bit)

**Additional context**

**Comment by msmolyakov** [comment]
Thanks for the report. We'll fix this in an upcoming release
