### ISSUE TITLE
[FEATURE] Мануал по сборке расширения из исходных кодов

### ISSUE THREAD

**Issue by yurial** [wavesplatform/waves-keeper#96]
**Аbstract**
Добавить в README инструкцию по сборке расширения CRX из исходных файлов.

**Motivation and Purposes**
Возможность использовать локально собранное расширение, в том числе отказаться от возможности автоматического обновления расширения.

**Specification**
Пошаговая инструкция, позволяющая собрать CRX файл.

**Backwards Compatibility**
Полная совместимость с предыдущими версиями.

**Examples and Implementation**

**Comment by msmolyakov** [comment]
@yurial для вас еще актуален этот тикет?
Почему вам необходимо собирать расширение локально и избегать автообновления? И для чего нужен именно CRX файл?

**Comment by yurial** [comment]
> @yurial для вас еще актуален этот тикет?
Да
>Почему вам необходимо собирать расширение локально и избегать автообновления?
Я параноик.
>И для чего нужен именно CRX файл?
Мне казалось, что расширения google chrome имеют именно такие расширения файла. В принципе, мне подойдет любой способ установки расширения из локальных файлов.

**Comment by msmolyakov** [comment]
Вы не сможете собрать CRX файл, т.к. он должен быть подписан приватным ключом издателя расширения.
Если соберете CRX файл неподписанный или же подписанный неправильным ключом, то у расширения будет отличаться ID. Chrome заблокирует работу этого расширения, т.к. Chrome WebStore нет расширения с таким ID.

Конечно, вы можете сделать dev-сборку. Но учтите, что она не будет защищена подписью. Поэтому Chrome не сможет вас предупредить, если в директории уже установленного расширения кто-то изменит его исходный код.

Если этот способ по-прежнему подходит, то:

1. установите NodeJS v10
2. в корне проекта выполните `npm ci && npm run dist`
3. в Chrome откройте `Menu -> More Tools -> Extensions`
4. включите "Developer mode"
5. нажмите "Load unpacked" и укажите путь до папки `./dist/chrome/`
Готово

**Comment by msmolyakov** [comment]
Закрыл ишью по ошибке. Если будут вопросы/предложения — откройте ишью снова или создайте новый.

Вероятно, в ближайшем будущем мы сделаем публикацию релизов на GitHub с приложенным CRX файлом.
